### PR TITLE
little skiddy boy forgot to put the most important

### PR DESCRIPTION
**Pull request by vibedivide**

### CODE REVIEW

**Comment by voept** [comment]
Did you not read it? I said this isn't my chatbox lmao, I even gave credit

**Comment by vibedivide** [comment]
💩

**Comment by voept** [comment]
Can you not take my stuff down, I have done ABSOLUTELY nothing to you, yet you continue to disrupt and cause chaos on my website, and for what reason? None.

**Comment by vibedivide** [comment]
give repl.it login 😈

**Comment by voept** [comment]
No.

**Comment by vibedivide** [comment]
😭

**Comment by voept** [comment]
You've got to be kidding, are you serious? Why do you keep shutting my sites down?

**Comment by vibedivide** [comment]
you take too much credit and fail to critique other peoples sites without saying flaws your own sites have

**Comment by vibedivide** [comment]
if its not even your own chatbox why upload it when someone can easily find it and steal it from a little tutorial you clinged to?

**Comment by vibedivide** [comment]
nobody will use it and especially not now loooool

**Comment by voept** [comment]
The chatbox was open source on repl.it

**Comment by voept** [comment]
And it's my website, why not take credit for it. Yes, I understand and see flaws, and they will be fixed by time. Please just don't take my sites down, I haven't done anything to you.

**Comment by vibedivide** [comment]
then keep the trash on repl.it

**Comment by vibedivide** [comment]
fixed by time you dont even know the basics of not making html errors

**Comment by voept** [comment]
Insulting my site so you feel better about yourself, huh? Just going to close the comments on this.

**Comment by vibedivide** [comment]
kek

**Pull request closed without merging**
